version: '0.1'
services:
  postgresql:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'

  redis:
    image: 'redis'

  server:
    build:
      context: .
      dockerfile: /backend/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgresql
      - redis
    