version: '3.8'
services:
  postgresql:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '7070:7070'
    depends_on:
      - postgresql

    