FROM rust:1.76-bookworm AS builder

WORKDIR /usr/src/rust_axum_service

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

# Install SELinux utilities
RUN apt-get update && apt-get install -y policycoreutils && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/rust_axum_service

COPY --from=builder /usr/src/rust_axum_service/target/release/boraxpr_rust_axum .

# Set correct SELinux context and permissions
RUN chmod +x /usr/src/rust_axum_service/boraxpr_rust_axum && \
    chcon -t usr_t /usr/src/rust_axum_service/boraxpr_rust_axum

EXPOSE 7070
CMD ["./boraxpr_rust_axum"]