FROM rust:1.76-bookworm

WORKDIR /usr/src/rust_axum_service

COPY . .

RUN cargo install cargo-watch

RUN cargo install sqlx-cli

EXPOSE 7070

CMD ["sh", "-c", "sqlx migrate run && cargo watch -x run"]